baseURL = "https://harshkishorani.github.io/"
languageCode = "en-us"
title = "Harsh Kishorani"
enableRobotsTXT = true
titleCaseStyle = "firstupper"
copyright = 'Harsh Kishorani'

[module]
  [[module.imports]]
    path = "github.com/michenriksen/hugo-theme-til"

[outputs]
  home = ['html']
  section = ['html', 'rss', 'json']
  page = ['html']

[frontmatter]
  lastmod = ["lastmod", "modified"]

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "/about"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    pageRef = "/posts"
    weight = 20

  [[menu.main]]
    identifier = "notes"
    name = "Notes"
    pageRef = "/notes"
    weight = 30

  [[menu.main]]
    identifier = "graph"
    name = "Graph"
    pageRef = "/graph"
    weight = 40

[markup]
  [markup.highlight]
    noClasses = false
    style = 'tokyonight-night'

  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.extensions]
        [markup.goldmark.extensions.passthrough]
          enable = true
          [markup.goldmark.extensions.passthrough.delimiters]
            block = [['\[', '\]'], ['$$', '$$']]
            inline = [['\(', '\)']]

      [markup.goldmark.parser.attribute]
        block = true

[params]
  math = false

  [params.author]
    name = "Harsh Kishorani"
    email = "hkishorani7@gmail.com"

  [params.footer]
    creativeCommonsLicense = 'by_sa'

  [params.robotstxt]
    blockCC = true
    blockAI = true

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true